# Generated by Django 5.0.6 on 2024-08-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='/c_images/default.jpg', upload_to='c_images'),
        ),
    ]
